name: Build and publish a docker image

on:
  release:
    types: [ published ]
  push:
    branches: [ master ]

jobs:
  docker_publish:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: lcsb-biocore/docker/fbcmodeltests.jl
          github_token: ${{ secrets.GITHUB_TOKEN }}
